//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pap_Diogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituiçao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instituiçao()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public string ID_Instituiçao { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public string Código_Postal { get; set; }
        public string Telefone { get; set; }
        public string Telemóvel { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> Data_de_registo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string C3_Words { get; set; }
        public Nullable<int> Concelho { get; set; }
    
        public virtual Concelho Concelho1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
