//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pap_Diogo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pap_DiogoEntities : DbContext
    {
        public pap_DiogoEntities()
            : base("name=pap_DiogoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concelho> Concelhoes { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<Instituiçao> Instituiçao { get; set; }
        public virtual DbSet<Raça> Raça { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
        public virtual DbSet<Utilizador_Animal> Utilizador_Animal { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Favorito> Favoritos { get; set; }
        public virtual DbSet<UtilizadorInteresse> UtilizadorInteresses { get; set; }
    
        public virtual ObjectResult<uspDadosUtilizador_Result> uspDadosUtilizador(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspDadosUtilizador_Result>("uspDadosUtilizador", idParameter);
        }
    
        public virtual ObjectResult<uspObterDadosUtilizador_Result> uspObterDadosUtilizador(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObterDadosUtilizador_Result>("uspObterDadosUtilizador", idParameter);
        }
    }
}
