//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pap_Diogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizadorInteresse
    {
        public int ID_UtilizadorInteresse { get; set; }
        public Nullable<int> Distrito { get; set; }
        public Nullable<int> Concelho { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Raça { get; set; }
        public string Idade { get; set; }
        public string Género { get; set; }
        public string Utilizador { get; set; }
        public string Porte { get; set; }
    
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
